script:
  - set -o pipefail && xcodebuild test -workspace Example/QuickTableView.xcworkspace -scheme QuickTableView-Example -destination 'platform=iOS Simulator,name=iPhone X' | bundle exec xcpretty
  - bundle exec pod install --repo-update
  - bundle exec pod lib lint

before_install:
  - gem update --system
  - gem install bundler

language: objective-c
osx_image: xcode9.2

